security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity: {
                class: App\Entity\Usuario,
                property: email
              }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            form_login:
                login_path: login # Rota do formulario de Login
                check_login: login # Rota onde vai verificar a autenticidade do usuario
                default_target_path: default # Depois que autenticar, vai para essa rota
                always_use_default_target_path: true # Toda vez que logar, ir para o target path
                username_parameter: email # padrao: _username
                password_parameter: senha # padrao: _password

            logout:
                path: /usuario/logout
                target: / # Depois de deslogar, para para essa rota

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: painel, roles: ROLE_ADMIN }

    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
            cost: 12