vich_uploader:
    db_driver: orm

    mappings:
        perfil_imagem:
            uri_prefix: /uploads/perfil
            upload_destination: '%kernel.project_dir%/public/uploads/perfil'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
